package com.ws.entity;

import lombok.Builder;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@Builder
public class PriceSec implements Serializable {

    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.c
     *
     * @mbg.generated
     */
    private String c;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.t
     *
     * @mbg.generated
     */
    private Long t;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.ts
     *
     * @mbg.generated
     */
    private String ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.p
     *
     * @mbg.generated
     */
    private Double p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.l
     *
     * @mbg.generated
     */
    private Double l;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.h
     *
     * @mbg.generated
     */
    private Double h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.o
     *
     * @mbg.generated
     */
    private Double o;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.buy
     *
     * @mbg.generated
     */
    private Double buy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.lc
     *
     * @mbg.generated
     */
    private Double lc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.zd
     *
     * @mbg.generated
     */
    private String zd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.sell
     *
     * @mbg.generated
     */
    private Double sell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.v
     *
     * @mbg.generated
     */
    private Double v;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.zdf
     *
     * @mbg.generated
     */
    private String zdf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.price_sec.crt_time
     *
     * @mbg.generated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.price_sec
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
